on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v2

      - name: Build Book
        uses: docker://raphaelborges/mdbook:1.0.1
        with:
          args: /github/workspace/pt
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./pt/book/i18n
          
      - name: Give execute permission
        run: chmod +x ./.github/workflows/copy.sh

      - name: Run the shell script
        run: sh ./.github/workflows/copy.sh